create table dwh.dwh_airlines_analysis
as
select 
fl.YEAR,
fl.MONTH,
fl.DAY,
fl.DAY_OF_WEEK,
fl.AIRLINE,
fl.FLIGHT_NUMBER,
fl.TAIL_NUMBER,
fl.ORIGIN_AIRPORT,
fl.DESTINATION_AIRPORT,
fl.SCHEDULED_DEPARTURE,
fl.DEPARTURE_TIME,
fl.DEPARTURE_DELAY,
fl.TAXI_OUT,
fl.WHEELS_OFF,
fl.SCHEDULED_TIME,
fl.ELAPSED_TIME,
fl.AIR_TIME,
fl.DISTANCE,
fl.WHEELS_ON,
fl.TAXI_IN,
fl.SCHEDULED_ARRIVAL,
fl.ARRIVAL_TIME,
fl.ARRIVAL_DELAY,
fl.DIVERTED,
fl.CANCELLED,
fl.CANCELLATION_REASON,
fl.AIR_SYSTEM_DELAY,
fl.SECURITY_DELAY,
fl.AIRLINE_DELAY,
fl.LATE_AIRCRAFT_DELAY,
fl.WEATHER_DELAY,
apt.AIRPORT as ORIGIN_AIRPORT_NAME,
apt.CITY as ORIGIN_AIRPORT_city,
apt.STATE as ORIGIN_AIRPORT_state,
apt.COUNTRY as ORIGIN_AIRPORT_country,
apt.LATITUDE as ORIGIN_AIRPORT_latitude,
apt.LONGITUDE as ORIGIN_AIRPORT_longitude,
aptd.AIRPORT as DESTINATION_AIRPORT_NAME,
aptd.CITY as DESTINATION_AIRPORT_CITY,
aptd.STATE as DESTINATION_AIRPORT_STATE,
aptd.COUNTRY as DESTINATION_AIRPORT_COUNTRY,
aptd.LATITUDE as DESTINATION_AIRPORT_LATITUDE,
aptd.LONGITUDE as DESTINATION_AIRPORT_LONGITUDE,
arl.AIRLINE as airline_name
from STG.STG_JFK_FLIGHTS fl
left join STG.stg_airports apt ON
fl.ORIGIN_AIRPORT = apt.IATA_CODE
left join STG.stg_airports aptd ON
fl.DESTINATION_AIRPORT = aptd.IATA_CODE
left join STG.STG_AIRLINES arl ON
fl.AIRLINE = arl.IATA_CODE